spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/jwt
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 60000
    max-lifetime: 1800000

# jwt
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
